data("warpbreaks")
head(warpbreaks)
summary(warpbreaks)
model1<- aov(breaks~wool+tension,data=warpbreaks)
summary(model1)
plot(model1)
model2<- aov(breaks~wool+tension+wool:tension,data=warpbreaks)
summary(model2)
plot(model2)

